### ISSUE TITLE
Cleaning up the React Upload Widget instance on unload

### ISSUE THREAD

**Issue by koren3210** [cloudinary-community/cloudinary-examples#64]
hey :)

i use the react upload widget in my app. 
i found that if i navigate from the upload page(in my app it /addnew) to the home page /   and the back the /addnew
the iframe is still exist as expected . but when i try to updateUrl state something related to the iframe is going wrong and the url state doesn't update. 

i have a temp fix for that. a clean function that destroy the widget when the location of the page is changing.

<img width="1792" alt="Screenshot 2023-10-04 at 0 49 37" src="https://github.com/cloudinary-community/cloudinary-examples/assets/85394450/81baf3bd-a658-4c98-8cf1-55d3e9f2ba69">

**Comment by colbyfayock** [comment]
hey @koren3210 thanks for sharing - what router are you using? i would suspect that part of the solution would be router dependent right? does the `unlisten` functionality properly work well for your use case? it likely makes sense that we should be cleaning up the instance in the examples as well

if you feel this is something we should add to our examples, would you want to create a pull request for all of the react-centric upload widget examples to include that?

* https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/react-upload-widget-preset/src/components/UploadWidget/UploadWidget.js
* https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/remix-upload-widget-preset/app/components/UploadWidget/index.jsx

There are also the Next.js examples, however those work slightly different since they take advantageof Next.js APIs for the loading aspect:
* https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/nextjs-upload-widget-preset/components/UploadWidget/UploadWidget.js
* https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/nextjs-upload-widget-signed/components/UploadWidget/UploadWidget.js

**Comment by JoshuaRotimi** [comment]
Hello @colbyfayock I'd like to work on this issue. If @koren3210 is not already on it. But before that, I would like to test out the issue and see if I can replicate it. Is there an npm package I can install to an existing project to test the issue?

**Comment by colbyfayock** [comment]
hey @JoshuaRotimi yup they havent answered in over a week so its all yours!

there's no npm package, this repository is a bunch of independent projects within the `examples` directory

the instructions should generally be in each folder's README but if you go clone this repo and navigate to that example, run `npm install`, and im thinking it's Create React App so run `npm run start`,  you should be able to get it up and running

you'll likely need to add your cloudinary credentials as environment variables as well

**Comment by JoshuaRotimi** [comment]
Quick question @colbyfayock , Is there a reason the `widget` variable is being stored outside the `UploadWidget` component? I think it causes an issue. 

The Issue - If you have two instances of the `UploadWidget` component on the page, with two different `handleUpload` functions that change a piece of state when the upload is successful, only the first upload function will be used every time giving a strange behaviour. Might be a reason why @koren3210 had that issue. 

This should explain it better - https://www.loom.com/share/16351971c85c460ea85f85ad7c1887ec

**Comment by koren3210** [comment]
Hey @JoshuaRotimi ,
I opened issue in the past.
I tried to tag you in the closed issue so you can see why he place the variables outside the function.

If the variables are inside the function so there was a problem of recreating the iframe instance when I navigate between pages in my app. 

Tell me if you can see the tag in the closed issue

**Comment by JoshuaRotimi** [comment]
Yes I have seen the tag, thanks @koren3210. But maybe the solution you suggested with the cleanup function in the useEffect may solve that problem?

**Comment by koren3210** [comment]
@JoshuaRotimi  
I tried now with the variables inside the uploadWidget and it keep the issue of creating instances every time I navigate back to the page.
Although the cleanup function 


When the variables are lifted out of the function it works properly.

**Comment by JoshuaRotimi** [comment]
That's strange @koren3210. The cleanup function should remove the instance when unmounted and create a new one when you navigate back to the page when the `widget` variable is inside the `uploadWidget` component. Is the issue creating a new instance or creating multiple instances ?

**Comment by colbyfayock** [comment]
hey before i dig into this, any updates? thanks Koren for filling in on the history of the changes. it's be tough finding a perfect solution for how to manage the instance of the widget

**Comment by JoshuaRotimi** [comment]
From my tests, removing the `widget` with the cleanup function will solve the problem of creating new instances  which (from my understanding) was the reason for putting the `widget` variable outside the `uploadWidget` component in the first place. With the widget variable inside the component, the problem I described earlier/in the video is resolved. Of course, I can make the PR and we can test it and see if all works well.

**Comment by koren3210** [comment]
<img width="1398" alt="Screenshot 2023-10-11 at 22 53 24" src="https://github.com/cloudinary-community/cloudinary-examples/assets/85394450/f62cb097-4a01-41ba-b40a-94ff01e8dbdb">

i tried again with the instance variables inside the function. and it does work properly.
