### ISSUE TITLE
[Example] Go - Adding an image as an overlay

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/cloudinary-examples#78]
Add an example as an executable script that adds an image as an overlay to an existing image in Go.

You can start off by replicating this folder and example from Node:

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-transformations-effects

Particularly the image-overlay.js file, but in Go.

**Comment by colbyfayock** [comment]
hey @sccalabr as mentioned in the other Issue, we can start with the other one in case someone wants to grab this one before you finish. if it's not claimed by the time the other is merged in, i can assign this one!

**Comment by rahul1995** [comment]
Hey, can I work on this?

**Comment by saisumith770** [comment]
@colbyfayock I was looking through the docs for writing transformations on the images and seems like we have to write a long string in the go library, reference -> https://cloudinary.com/documentation/go_media_transformations#direct_url_building. I tried to write a transformation query replicating the operations as in the nodejs-transformations-effects, reference -> https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/node-transformations-effects/image-overlay.js . Below is the query:
"c_fill,h_600,w_600,g_auto,l_examples/sale-tag,w_100,h_100,fl_layer_apply,g_north_east,x_10,y_10"
since I'm new to this I do not know if the query is correct. Could you please verify it.

**Comment by colbyfayock** [comment]
@saisumith770 yeah that seems to be the case, didn't realize that myself

the string you pasted is ALMOST right, just a few tweaks. here's the one from Node, you can use this:

```
c_fill,g_auto,h_600,w_600/h_100,l_examples:sale-tag,w_100/fl_layer_apply,g_north_east,x_10,y_10
```

the full URL from that example:

https://res.cloudinary.com/colbycloud-examples/image/upload/c_fill,g_auto,h_600,w_600/h_100,l_examples:sale-tag,w_100/fl_layer_apply,g_north_east,x_10,y_10/v1/examples/shoes_kto0zb

**Comment by colbyfayock** [comment]
i assigned you the issue since you appear to be working on it, lmk if you aren't working on it though

**Comment by saisumith770** [comment]
@colbyfayock  I've created a PR #94 could you kindly review it. Do let me know if any changes are required.
